### PR TITLE
Error when trying to expand menu by ID

### PR DESCRIPTION
**Pull request by DeboraCamargo**
When trying to expand the menu by a given ID it is not opening the second time

### CODE REVIEW

**Comment by ShankyTiwari** [comment]
Hi @DeboraCamargo Thanks for the PR, I will check this today.

**Comment by Sucramx** [comment]
@ShankyTiwari By any chance did you get to look at this yet? I am just wondering because I am having the same issue and would love to see it get resolved! Let me know 👍

**Review by ShankyTiwari — APPROVED** [review]

**Comment by ShankyTiwari** [comment]
Published in v6.0.1, Sorry for the delay.

Thanks

**Comment by ShankyTiwari** [comment]
There was a slight issue with this PR, the expanded menus were not collapsing hence I have reverted for now. But I check this issue further and will try to push a patch this week. 

In interested in the issue and wanna give it a try, please check from this sha: [5e371712f6bb278a812b991c28fa74d16e0dc734](https://github.com/ShankyTiwari/ng-material-multilevel-menu/commit/5e371712f6bb278a812b991c28fa74d16e0dc734)

Thanks

**Comment by ShankyTiwari** [comment]
Tracked here #225

**Pull request merged**
